### ISSUE TITLE
Mac builds failure investigation

### ISSUE THREAD

**Issue by thekingofcity** [linebender/resvg#902]
After some investigation into the Mac build/release failure, here are the findings and possible solutions:

#### 🔍 Findings

1. **`Install QT: ERROR: Failed building wheel for pyzstd` in `v0.45.0` official pipeline**  
   This error occurs during the `jurplel/install-qt-action` step.  
   ✅ **Fix:** Upgrade to `jurplel/install-qt-action@v4`.

2. Then **`Project ERROR: failed to parse default search paths from compiler output`on next step `Build viewsvg`**
   This error is caused by an incompatibility with **default Xcode 15** on [`macos-13` image](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode).  
   - See QT bug: [QTBUG-117225](https://bugreports.qt.io/browse/QTBUG-117225)
   - This issue is only fixed in **Qt 5.15.15** or higher, which is a **paid version**.
   - `aqtinstall` does not support downloading paid versions. See: miurahr/aqtinstall#636

#### ✅ Options

1. **Ignore `viewsvg` builds on Mac**  
   - `resvg` continues to work fine.  
   - Easiest path forward.

2. **Upgrade to Qt 6**  
   - This issue is fixed in Qt 6.  
   - ⚠️ Significant migration effort required.

3. **Force Xcode 14 on `macos-13` image**  
   - Forked builds using this setup are working successfully. See [my fork builds](https://github.com/thekingofcity/resvg/actions/runs/14436506271). And [code changes](https://github.com/thekingofcity/resvg/blob/21fb57e5bd56bc040a740d80c92f07d4decbe84a/.github/workflows/main.yml#L16).
   - ✅ Viable short-term fix with minimal changes.

Let me know which path we’d like to proceed with. I'm happy to open a pull request for option 1 or 3 if that is preferred :)

**Comment by DJMcNab** [comment]
Thanks for digging into this.

My impulse here is to remove the QT integration from this repository entirely (if anyone needs it, they can vendor it themselves). This would be for similar reasons as #897, that we don't have the will to maintain it, and it's causing us issues.
(To be entirely clear, I am **NOT** proposing to remove the C api, which the QT integration itself uses).

If at a later point, someone who is motivated to restore viewsvg chooses to do so, we'd happily engage with that. Ideally, we'd have a test integration of the C API in this repository as well (but removing `viewsvg` doesn't meaningfully change that state, because we don't test it in CI except on a release).

**Comment by LaurenzV** [comment]
I think I also agree, if @RazrFalcon is fine with this.

**Comment by RazrFalcon** [comment]
`usvg` doesn't depend on Qt, so it's not an issue.
For now, we can simply skip building `tools/viewsvg`, this way we would not need Qt.

**Comment by thekingofcity** [comment]
> `usvg` doesn't depend on Qt, so it's not an issue. For now, we can simply skip building `tools/viewsvg`, this way we would not need Qt.

Sorry it's `viewsvg`, I corrected the type in the body.

**Comment by thekingofcity** [comment]
I opened a pull request simply by skipping the build of `viewsvg` on mac. I Hope this change could result in a successful shipment of `resvg` and `usvg` on mac in the next tagged release.

**Comment by Kidev** [comment]
Saw the issue about `aqtinstall` not supporting paid versions being referenced here. Our bad, this issue is closed but still appears front and center since it was never unpinned.  

The latest versions of `aqtinstall` DO SUPPORT paid versions installation of Qt easily. `v3.2.2` is not yet released but `master` have, in addition to the official installer features described in [the dedicated documentation page](https://aqtinstall.readthedocs.io/en/latest/official.html#), the option `--use-official-installer [email pw]` that can simply be appended to your existing `aqt` commands. See [here for details on this option](https://github.com/miurahr/aqtinstall/pull/906).

**Comment by RazrFalcon** [comment]
@Kidev we do not need paid versions of Qt. The whole issue is due to the fact that the code still uses Qt 5, but `install-qt-action` fails to install it for some reason.

**Comment by Kidev** [comment]
> [@Kidev](https://github.com/Kidev) we do not need paid versions of Qt. The whole issue is due to the fact that the code still uses Qt 5, but `install-qt-action` fails to install it for some reason.

Both `aqtinstall` and `install-qt-action` should support the latest open source Qt 5 versions, so that's weird. I can take a look at some Action logs if you can point me to one failed run for this reason.

Also, I quickly took a look at `viewsvg` source, and I feel like this would compile easily on Qt 6, with only one change to your viewsvg.pro (widgets is no longer part of `gui`):
```cmake
QT += core gui widgets

greaterThan(QT_MAJOR_VERSION, 5): QT += widgets

TARGET = viewsvg
TEMPLATE = app
CONFIG += c++20
```

It worked well, only got one warning (`Qt::AA_EnableHighDpiScaling` is deprecated).

After editing the viewsvg.pro, to build I did this:
```console
kidev:~$ cargo build --release -p resvg-capi
kidev:~$ cd tools/viewsvg
kidev:~$ qmake6 viewsvg.pro
kidev:~$ LD_LIBRARY_PATH=../../target/release make
```

It compiled and running `viewsvg` displayed a GUI

**Comment by RazrFalcon** [comment]
Patches are welcome.

**Comment by Kidev** [comment]
[Here you go](https://github.com/thekingofcity/resvg), did it on your fork though
